export const scenes = [
  { id: 'silence', source: 'idea-3.png', name: 'The quiet within', label: 'CHAPTER ONE', title: ['Timeless places,', 'endless stories.'], description: ['Wander gently.', 'Listen deeply.'], inscription: '無聲之境', align: 'left', x1: 916, x2: 1594, count: 39, anchor: u => 445 - u * 49, length: (u,i) => 270 + 260 * Math.abs(Math.sin(i * 1.81)) + 35 * Math.sin(i * .5) },
  { id: 'whisper', source: 'idea-5.png', name: 'A passing whisper', label: 'CHAPTER TWO', title: ['Some places', 'speak in whispers', 'only the heart', 'can hear.'], description: ['Travel not to escape,', 'but to remember.'], inscription: '風之詩', align: 'left', x1: 932, x2: 1518, count: 35, anchor: u => 365 + 63 * Math.pow(Math.abs(2 * u - 1), .7), length: (u,i) => 220 + 310 * Math.sin(u * Math.PI) + 56 * Math.sin(i * 1.82) },
  { id: 'sky', source: 'idea-4.png', name: 'Beneath the same sky', label: 'CHAPTER THREE', title: ['Where eaves hold', 'the sky, and time', 'moves like drifting cloud.'], description: ['Beneath the roof of quiet grandeur,', 'stories travel far and return as mist.', 'Listen to what the distance remembers.'], inscription: '萬物靜觀皆自得', align: 'right', x1: 354, x2: 1092, count: 38, anchor: () => 470, length: (u,i) => 170 + 315 * Math.abs(Math.sin(i * 1.42)) },
  { id: "landscape", source: "idea-1.png", name: "Silent landscapes", label: "CHAPTER FOUR", title: ["Timeless", "stories, silent", "landscapes."], description: ["Wander through places where time slows down", "and every path carries a quiet story."], inscription: "無聲之境", align: "left", x1: 1226, x2: 1480, count: 19, anchor: u => 390 + u * 5, length: (u,i) => 300 + 270 * Math.abs(Math.sin(i * 1.43)) },
  { id: "rain", source: "idea-2.png", name: "Borrowed silence", label: "CHAPTER FIVE", title: ["Between gates,", "rain, and", "borrowed silence."], description: ["Some places do not call for answers.", "They ask only", "that you slow down enough to listen."], inscription: "間の美學", align: "right", x1: 534, x2: 870, count: 24, anchor: u => 359 + 12 * Math.sin(u * Math.PI), length: (u,i) => 270 + 295 * Math.abs(Math.sin(i * 1.71)) },
  { id: "memory", source: "idea-6.png", name: "Paths remembered", label: "CHAPTER SIX", title: ["Paths remembered,", "stories remain."], description: ["Some places stay with us,", "long after we leave."], inscription: "記憶風景", align: "left", x1: 996, x2: 1788, count: 32, anchor: () => 383, length: (u,i) => 265 + 275 * Math.abs(Math.sin(i * 1.88)) },
  { id: "journey", source: "idea07.png", name: "A path to be felt", label: "CHAPTER SEVEN", title: ["Not every journey", "needs a destination."], description: ["Some paths are meant", "to be felt, not found."], inscription: "行在途中", align: "left", x1: 1047, x2: 1354, count: 19, anchor: () => 417, length: (u,i) => 155 + 150 * Math.abs(Math.sin(i * 1.75)) },

];
export const poem = '山川異域風月同天行到水窮處坐看雲起時空山不見人但聞人語響明月松間照清泉石上流白雲深處有人家春風又綠江南岸';
